=== dannyarcher/metadata/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "definitions": {
        "agent": {
            "oneOf": [
                {
                    "type": "object",
                    "properties": {
                        "person": {
                            "type": "object",
                            "properties": {
                                "surname": {
                                    "type": "string"
                                },
                                "firstname": {
                                    "type": "string"
                                },
                                "email": {
                                    "type": "string"
                                },
                                "organisation": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false,
                            "minProperties": 1
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "person"
                    ]
                },
                {
                    "type": "object",
                    "properties": {
                        "organisation": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "name"
                            ],
                            "additionalProperties": false
                        }
                    },
                    "additionalProperties": false,
                    "required": [
                        "organisation"
                    ]
                }
            ]
        },
        "W3CDate": {
            "type": "string",
            "pattern": "/(\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+)|(\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d)|(\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d)/"
        },
        "url": {
            "type": "string",
            "pattern": "^(?:(?:https?|ftp)?:?\\/\\/)(?:\\S+(?::\\S*)?@)?(?:(?!(?:10|127)(?:\\.\\d{1,3}){3})(?!(?:169\\.254|192\\.168)(?:\\.\\d{1,3}){2})(?!172\\.(?:1[6-9]|2\\d|3[0-1])(?:\\.\\d{1,3}){2})(?:[1-9]\\d?|1\\d\\d|2[01]\\d|22[0-3])(?:\\.(?:1?\\d{1,2}|2[0-4]\\d|25[0-5])){2}(?:\\.(?:[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-4]))|(?:(?:[a-z\\u00a1-\\uffff0-9]+-?)*[a-z\\u00a1-\\uffff0-9]+)(?:\\.(?:[a-z\\u00a1-\\uffff0-9]+-?)*[a-z\\u00a1-\\uffff0-9]+)*(?:\\.(?:[a-z\\u00a1-\\uffff]{2,})))(?::\\d{2,5})?(?:\\/[^\\s]*)?$"
        },
        "mimetype": {
            "type": "string",
            "pattern": "[\\w+\\*-]+/[\\w\\*+-]+"
        },
        "fileCollection": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 999
                },
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/file"
                    }
                }
            },
            "required": [
                "version",
                "files"
            ]
        },
        "file": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 999
                },
                "migrationAction": {
                    "type": "object",
                    "properties": {
                        "pathway": {
                            "$ref": "#/definitions/url"
                        },
                        "agent": {
                            "$ref": "#/definitions/agent"
                        },
                        "generated": {
                            "$ref": "#/definitions/W3CDate"
                        }
                    }
                },
                "format": {
                    "type": "string"
                },
                "mimetype": {
                    "$ref": "#/definitions/mimetype"
                },
                "filesize": {
                    "type": "number",
                    "minimum": 0
                }
            }
        }
    },
    "type": "object",
    "properties": {
        "title": {
            "type": "string"
        },
        "created": {
            "$ref": "#/definitions/W3CDate"
        },
        "creators": {
            "type": "array",
            "items": {
                "items": {
                    "$ref": "#/definitions/agent"
                }
            }
        },
        "recipients": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/agent"
            }
        },
        "attachedTo": {
            "type": "string"
        },
        "versions": {
            "oneOf": [
                {
                    "type": "array",
                    "items": [
                        {
                            "$ref": "#/definitions/file"
                        },
                        {
                            "$ref": "#/definitions/fileCollection"
                        }
                    ]
                }
            ]
        },
        "series": {
            "type": "number"
        },
        "disposalRule": {
            "type": "object",
            "properties": {
                "authority": {
                    "type": "string"
                },
                "class": {
                    "type": "string"
                }
            },
            "required": [
                "authority",
                "class"
            ],
            "additionalProperties": false
        },
        "accessRule": {
            "type": "object",
            "properties": {
                "accessDirection": {
                    "type": "number"
                },
                "effect": {
                    "type": "string",
                    "enum": [
                        "Early",
                        "OPA",
                        "CPA"
                    ]
                },
                "calculateFrom": {
                    "$ref": "#/definitions/W3CDate"
                }
            },
            "required": [
                "accessDirection",
                "effect",
                "calculateFrom"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "title",
        "series",
        "disposalRule",
        "accessRule"
    ],
    "additionalProperties": false
}

=== dannyarcher/metadata/samples/1.json
{
  "title": "The Danny Archer Files",
  "creators": [
    {
      "organisation": {
        "name": "Lehane Corp."
      }
    }
  ],
  "recipients": [
    {
      "organisation": {
        "name": "The Findlay Group"
      }
    }
  ],
  "attachedTo": "incomprehensiblestring983",
  "versions": [
    {
      "version": 0,
      "format": "fmt/40",
      "mimetype": "application/msword",
      "filesize": 91648
    },
    {
      "version": 1,
      "migrationAction": {
        "pathway": "http://digitalarchives.records.nsw.gov.au/pathways/15",
        "agent": {
          "organisation": {
            "name": "State Records Authority of NSW"
          }
        },
        "generated": "2014-01-13T00:00:00.000Z"
      },
      "format": "fmt/18",
      "mimetype": "applicaton/pdf",
      "filesize": 160681
    }
  ],
  "series": 1,
  "disposalRule": {
    "authority": "GA28",
    "class": "1.1.1"
  },
  "accessRule": {
    "accessDirection": 1,
    "effect": "OPA",
    "calculateFrom": "2013-10-31T00:00:00.000Z"
  }
}

=== dannyarcher/metadata/samples/4.json
{
  "title": "Object with creators & recipients",
  "created": "2000-01-01T00:00:00.000Z",
  "creators": [
    {
      "person": {
        "surname": "Name",
        "firstname": "N"
      }
    }
  ],
  "recipients": [
    {
      "person": {
        "email": "person1@example.com"
      }
    },
    {
      "person": {
        "email": "person1@example.com"
      }
    },
    {
      "person": {
        "email": "person1@example.com"
      }
    }
  ],
  "versions": [
    {"version": 0, "files": [{"name":"file.pdf", "path":[], "fileSize": 100000,"format": "fmt/17","mimeType": "application/pdf"} ]},
    {"version": 1, "files": [{"name":"file.pdf", "path":[], "fileSize": 100033,"format": "fmt/17","mimeType": "application/pdf"} ]}
  ],
  "series": 99999,
  "disposalRule": {
    "authority": "GA28",
    "class": "1.1.1"
  },
  "accessRule": {
    "accessDirection": 99999,
    "effect": "OPA",
    "calculateFrom": "2000-01-01T00:00:00.000Z"
  }
}

=== dannyarcher/metadata/samples/3.json
{
  "title": "Multifile Example",
  "created": "2013-01-01T00:00:00.000Z",
  "creators": [
    {
      "organisation": {
        "name": "Multifile"
      }
    }
  ],
  "versions": [
    {
      "version": 0,
      "files": [
        {
          "name":"file.pdf", 
          "path":[],
          "fileSize": 37752481,
          "format": "fmt/17",
          "mimeType": "application/pdf"
        }
      ]
    },
    {
      "version": 1,
      "files": [
        {
          "name":"file.pdf", 
          "path":[],
          "fileSize": 3775248100,
          "format": "fmt/17",
          "mimeType": "application/pdf"
        }
      ]
    },
    {
      "version": 2,
      "files": [
        {
          "name":"file.pdf", 
          "path":[],
          "fileSize": 3775248100,
          "format": "fmt/17",
          "mimeType": "application/pdf"
        }
      ]
    }
  ],
  "series": 999999,
  "disposalRule": {
    "authority": "GA28",
    "class": "1.1.1"
  },
  "accessRule": {
    "accessDirection": 9999999,
    "effect": "Early",
    "calculateFrom": "2013-01-01T00:00:00.000Z"
  }
}

=== dannyarcher/metadata/samples/2.json
{
  "title": "Multifile Example",
  "created": "2013-01-01T00:00:00.000Z",
  "creators": [
    {
      "organisation": {
        "name": "Multifile"
      }
    }
  ],
  "versions": [
    {
      "version": 0,
      "files": [
        {
          "filesize": 37752481,
          "format": "fmt/17",
          "mimetype": "application/pdf"
        }
      ]
    }
  ],
  "series": 999999,
  "disposalRule": {
    "authority": "GA28",
    "class": "1.1.1"
  },
  "accessRule": {
    "accessDirection": 9999999,
    "effect": "Early",
    "calculateFrom": "2013-01-01T00:00:00.000Z"
  }
}
